spring:
  application:
    name: discovery

server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka